GET http://localhost:1111/

###
GET http://localhost:1111/news/ghana-web/NewsArchive/most-read

###
GET http://localhost:1111/news/ghana-web/NewsArchive/latest

###
GET http://localhost:1111/news/ghana-web/NewsArchive/archive?date=Aug 18, 2020

###
GET http://localhost:1111/news/ghana-web/article?link=https://www.ghanaweb.com/GhanaHomePage/NewsArchive/COVID-19-Ghana-receives-1-3-million-Pfizer-vaccines-from-US-1375840